const mongoose = require('mongoose')

const eventPlacesModal = new mongoose.Schema({
    title:{
        type:String,
        required:true
    },
    price:{
        type:Number,
        required:true
    },
    business_category:{
        type:mongoose.Schema.Types.ObjectId,
        ref:'businesscategory'
    },
    business_group:{
        type:mongoose.Schema.Types.ObjectId,
        ref:'businessgroup'
    },
    rating:{
        type:String,
    },
    price_per_plate:{
        type:Number,
    },
    guest_limit:{
        type:Number
    },
    discount:{
        type:Number,
        required:true
    },
    shortDiscription:{
        type:String,
        required:true
    },
    longDiscription:{
        type:String,
        required:true
    },
    address1:{
        type:String,
    },
    address2:{
        type:String,
    },
    pincode:{
        type:Number,
    },
    area:{
        type:mongoose.Schema.Types.ObjectId,
        ref:'areaModal'
    },
    landmark:{
        type:String,
    },
    city:{
        type:mongoose.Schema.Types.ObjectId,
        ref:'locations'
    },
    state:{
        type:mongoose.Schema.Types.ObjectId,
        ref:'state'
    },
    country:{
        type:mongoose.Schema.Types.ObjectId,
        ref:'country'
    },
    phonenumber:{
        type:Number,
    },
    status:{
        type:String,
    },
    room_price:{
        type:Number
    },
    total_rooms:{
        type:Number,
    },
    food_category:{
        type:String
    },
    image:[
            {
                url:String,
                public_id:String
            }
        ]
    
},{timestamps:true})

module.exports = mongoose.model('eventPlacesModal',eventPlacesModal)